[meta]
name     = "Record Raw Vehicle Data"
author   = "XertroV"
category = "Replay"
version  = "0.2.3"
siteid   = 261

[script]
#__DEFINES__
# dependencies = ["MLHook", "MLFeedRaceData", "VehicleState"]  # Might add respawn events or something in the future. I expect it's easy enough to infer from data, tho.
dependencies = ["VehicleState"]
